development:
  adapter: postgresql
  database: dailyboost_development
  username: dailyboost
  password:
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: dailyboost_test
  username: dailyboost
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dailyboost_production
  username: dailyboost
  password:
  pool: 5
  timeout: 5000
